### ISSUE TITLE
Similar solution to MacOS

### ISSUE THREAD

**Issue by goon94** [matega/hid_mimouse#1]
Is there any similar solution to MacOS?

**Comment by matega** [comment]
I have no idea, I don't have a Mac. I'd try this with the proper descriptor: https://github.com/thefloweringash/iousbhiddriver-descriptor-override

**Comment by aleksandrs-ledovskis** [comment]
Wanted to share another solution, albeit with caveat - [SteerMouse](https://www.plentycom.jp/en/steermouse/index.html) fixes the issue without any legacy macOS kernel extensions.

Downside is that it's not OSS and licence costs (19 USD) more than mouse itself.
