### ISSUE TITLE
Why doesn't this work anymore?

### ISSUE THREAD

**Issue by lostinasia123** [matega/hid_mimouse#5]
This worked great until a few kernel upgrades ago but hasn't been working lately.  I tried uninstalling from dkms, downloading the files again and doing the whole install process process over, but it still doesn't work.  I tried using xev to see if the side buttons were registering at all and they are not, both with the module removed and reinstalled.  Any ideas how to fix?

**Comment by lostinasia123** [comment]
I'm on 5.16.10-arch1-1

**Comment by lostinasia123** [comment]
~ $ dkms status
hid_mimouse/1.0, 5.16.10-arch1-1, x86_64: installed (original_module exists)

**Comment by matega** [comment]
I don't know, sorry, it works for me on Ubuntu 5.13.0-28-generic. Does the module get loaded when the mouse connects? What does `dmesg | grep mouse` and `lsmod | grep hid_mimouse` say?

I've had problem with secure boot being enabled and module signing not working out of the box, so the kernel refuses to load the unsigned module. Maybe it's that?

**Comment by lostinasia123** [comment]
Hey sorry to get back so late.  So dmesg returns:

~ $ sudo dmesg |grep mouse
[    3.791432] mousedev: PS/2 mouse device common for all mice
[  488.802350] mi-silent-mouse 0005:2717:5014.0002: input,hidraw1: BLUETOOTH HID v7.d4 Mouse [Mi Silent Mouse] on 0c:54:15:69:e8:6b

and lsmod returns:

hid_mimouse            16384  0
~ $ 

And everything works except the button swap on the side

**Comment by lostinasia123** [comment]
Oh man.  It just started working.  I have no idea why.  Maybe an update.  All's good now.  Thanks for your help and your hack.
